In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D

In [ ]:
import tensorflow as tf

import tensorflow_datasets as tfds
imdb, info = tfds.load("imdb_reviews/subwords8k", with_info=True, as_supervised=True)

In [ ]:
train_data, test_data = imdb['train'], imdb['test']

In [ ]:
tokenizer = info.features['text'].encoder

In [ ]:
train_data = train_data.padded_batch(64, tf.compat.v1.data.get_output_shapes(train_data))
test_data = test_data.padded_batch(64,  tf.compat.v1.data.get_output_shapes(test_data))

In [ ]:
for item in train_data:
  print(item)

(<tf.Tensor: shape=(64, 1109), dtype=int64, numpy=
array([[  62,   18,   41, ...,    0,    0,    0],
       [  12,   31,   93, ...,    0,    0,    0],
       [ 636,  102, 4714, ...,    0,    0,    0],
       ...,
       [ 133, 1955,    5, ...,    0,    0,    0],
       [2635, 1610,   48, ...,    0,    0,    0],
       [  12,  196, 7968, ...,    0,    0,    0]])>, <tf.Tensor: shape=(64,), dtype=int64, numpy=
array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1])>)
(<tf.Tensor: shape=(64, 1179), dtype=int64, numpy=
array([[3943,    4,  848, ...,    0,    0,    0],
       [1646, 1760,  463, ...,    0,    0,    0],
       [1993,   38,  601, ...,    0,    0,    0],
       ...,
       [  12,   81,  196, ...,    0,    0,    0],
       [3404, 5426, 7961, ...,    0,    0,    0],
       [ 156,    1, 4030, ...,    0,    0,    0]])>, <tf.Ten

In [ ]:
# Xây dựng model

# FIXME: Tạo model Sequential

model = Sequential()

# FIXME: Thêm một lớp Embedding

model.add(Embedding(tokenizer.vocab_size,64))

model.add(GlobalAveragePooling1D()) # Ta hoàn toàn có thể sử dụng một lớp Convolution 1D sau embedding để tìm mối quan hệ giữa các từ

# FIXME: Thêm một lớp Dense, chú ý có activation

model.add(Dense(6,activation='relu'))

# FIXME: Thêm một lớp Dense cuối, chú ý có activation

model.add(Dense(1,activation='sigmoid'))

In [ ]:
num_epochs = 10

# FIXME: Compile Optimizer và Loss function

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# FIXME: Tiến hành training. Mục tiêu: 87 %

history = model.fit(train_data,epochs=num_epochs,validation_data=test_data)

Epoch 1/10
391/391 [==============================] - 19s 47ms/step - loss: 0.6726 - accuracy: 0.6197 - val_loss: 0.6182 - val_accuracy: 0.6930
Epoch 2/10
391/391 [==============================] - 18s 47ms/step - loss: 0.5034 - accuracy: 0.8023 - val_loss: 0.4277 - val_accuracy: 0.8412
Epoch 3/10
391/391 [==============================] - 19s 48ms/step - loss: 0.3550 - accuracy: 0.8745 - val_loss: 0.3509 - val_accuracy: 0.8668
Epoch 4/10
391/391 [==============================] - 20s 50ms/step - loss: 0.2889 - accuracy: 0.8968 - val_loss: 0.3233 - val_accuracy: 0.8739
Epoch 5/10
391/391 [==============================] - 19s 47ms/step - loss: 0.2520 - accuracy: 0.9094 - val_loss: 0.3122 - val_accuracy: 0.8762
Epoch 6/10
391/391 [==============================] - 18s 46ms/step - loss: 0.2266 - accuracy: 0.9181 - val_loss: 0.3089 - val_accuracy: 0.8778
Epoch 7/10
391/391 [==============================] - 19s 50ms/step - loss: 0.2072 - accuracy: 0.9255 - val_loss: 0.3102 - val_accuracy: