Stochastic Gradient Descent

In [1]:
import numpy as np

In [2]:
X = np.array([
  [2],
  [7],
  [9],
  [3],
  [10],
  [6],
  [1],
  [8]            
]
)

In [3]:
y = np.array(
    [
     [13],
     [35],
     [41],
     [19],
     [45],
     [28],
     [10],
     [55],

    ]
)

In [4]:
ones = np.ones_like(X)

In [5]:
X = np.concatenate((X, ones), axis=1)

In [6]:
X

array([[ 2,  1],
       [ 7,  1],
       [ 9,  1],
       [ 3,  1],
       [10,  1],
       [ 6,  1],
       [ 1,  1],
       [ 8,  1]])

In [7]:
X[1]

array([7, 1])

In [8]:
def predict(theta, x):
  return x.T.dot(theta)

In [9]:
def cost(X, y, theta, m):
  return 1/(2 *m)* np.sum((X.dot(theta) - y)**2)

In [10]:
from sklearn.utils import shuffle

In [11]:
def SGD(X, y, theta, learning_rate, epochs):
  
  print(X, y)
  # Step 2: Update theta
  m = len(X)
  for i in range(epochs):
    # Step 1: Shuffle dataset
    X, y = shuffle(X, y)
    for k in range(m):
      error = predict(theta, X[k]) - y[k]
      for j in range(len(theta)):
        theta[j] = theta[j] - learning_rate * error * X[k][j]
    if (i + 1) % 100 == 0:
      print("Loss is {}".format(cost(X, y, theta, m)))

In [12]:
theta = np.random.normal(size=2).reshape((2, 1))

In [13]:
epochs = 3000
learning_rate = 0.001

In [14]:
SGD(X, y, theta, learning_rate, epochs)

[[ 2  1]
 [ 7  1]
 [ 9  1]
 [ 3  1]
 [10  1]
 [ 6  1]
 [ 1  1]
 [ 8  1]] [[13]
 [35]
 [41]
 [19]
 [45]
 [28]
 [10]
 [55]]
Loss is 18.116057305967317
Loss is 17.540266448247035
Loss is 17.15927313168504
Loss is 16.872864207469956
Loss is 16.681364790288683
Loss is 16.574082426812673
Loss is 16.472152914015638
Loss is 16.402638233125263
Loss is 16.358558276167898
Loss is 16.329286942585803
Loss is 16.318946091665083
Loss is 16.295781168041447
Loss is 16.286172946462393
Loss is 16.313279998875263
Loss is 16.276437642562183
Loss is 16.27030843545096
Loss is 16.267772263789315
Loss is 16.29114134959235
Loss is 16.267960886854322
Loss is 16.26630340745385
Loss is 16.27461962176341
Loss is 16.26632024349916
Loss is 16.285062678994066
Loss is 16.26414629740062
Loss is 16.277453011187358
Loss is 16.264335912150063
Loss is 16.26366352482577
Loss is 16.26659119228421
Loss is 16.29756243688057
Loss is 16.273211260726452


In [15]:
predict(theta, np.array([40, 1]))

array([182.52305153])

In [ ]:
X[0].shape

(2,)